package errors_test

import (
	"testing"
)

func TestRecover(t *testing.T)  {
	LogErr()
}
